### ISSUE TITLE
[Suggestion] Publish in the Chrome Web Store

### ISSUE THREAD

**Issue by remiroyc** [nebulasio/WebExtensionWallet#17]
Please, you need to publish your nebulas extension in the Chrome Web Store.
It would be easier for users to install it.

https://developer.chrome.com/webstore/publish

**Comment by yupnano** [comment]
Thank you for this suggestion. I have tried it. And I need to pay $5 to register as an developer, however, google pay don't support credit card of China Mainland. 
I will try it again later.

**Comment by remiroyc** [comment]
I live in Europe. If you need help to get a licence, send me an email at
remi.roycourt@hackandcraft.io

2018-05-17 14:25 GMT+02:00 yupnano <notifications@github.com>:

**Comment by ChengOrangeJu** [comment]
@remiroyc Thanks for the advice. @yupnano let's try it tomorrow :)

**Comment by Olovorr** [comment]
If you'd need help publishing it, I can help as well. It is just so crucial to have this extension available for the people without dev background. Also it looks shady when it is not officially release, i.e. this conversation happened to me just now:
<img width="812" alt="screen shot 2018-05-21 at 18 20 45" src="https://user-images.githubusercontent.com/15366622/40318211-2ceca1d4-5d24-11e8-8a3b-c2cd33f96a1f.png">

**Comment by ChengOrangeJu** [comment]
@Olovorr Will have a team internal discussion about it tomorrow and will let you know the result, thanks so much for the information

**Comment by yupnano** [comment]
I have submitted the extension to chrome store, and it was rejected. Then I made some changes and re-submitted it, it's now under review.

And BTW, it's published on my own an a individual developer, not published by Nebulas official.

**Comment by remiroyc** [comment]
Great news. I think it'd be better to submit it with official nebulas account. Because it'll instill confidence

**Comment by Olovorr** [comment]
Any progress here? 😢

**Comment by yupnano** [comment]
It was rejected again with no reason. :

**Comment by Olovorr** [comment]
I know this is really annoying, but we should really push for this. Is there anything I can do?

And why is it not possible for Nebulas to back this extension as a official Nebulas extension wallet? 🤔 Would be good for adoption in community.

**Comment by Olovorr** [comment]
@yupnano This can be closed right? 🙂 

Link: https://chrome.google.com/webstore/detail/nasextwallet/gehjkhmhclgnkkhpfamakecfgakkfkco

**Comment by yupnano** [comment]
sure, this should be closed now.
