### ISSUE TITLE
win10 defender报毒

### ISSUE THREAD

**Issue by sheiy** [nebulasio/WebExtensionWallet#9]

**Comment by yupnano** [comment]
应该是误报吧，也可能是之前的代码会导致误报。现在应该没问题了，社区群里也没有其他人反馈这样的问题，应该是偶然现象吧。
对了，现在重新pull代码还有报毒吗？

**Comment by Comup-X** [comment]
![image](https://user-images.githubusercontent.com/12210038/40093460-eca7986e-58f4-11e8-927e-c51976fb3aa1.png)
